# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZKaYFDAgX3T6iTASscTgck4Kazq8i3A
"""

import numpy as np
import pandas as pd

# 1. 自動生成實驗數據集 (二元分類)
np.random.seed(42)
X = np.random.randn(200, 2)
# 建立一個圓形的非線性邊界
y = (X[:, 0]**2 + X[:, 1]**2 < 1.2).astype(int).reshape(-1, 1)

# 儲存為 data.csv
df = pd.DataFrame({'x1': X[:, 0], 'x2': X[:, 1], 'label': y.flatten()})
df.to_csv('data.csv', index=False)
print("成功生成資料檔: data.csv")

# 2. 建立簡易類神經網路模型
class NeuralNetwork:
    def __init__(self):
        # 權重初始化
        self.W1 = np.random.randn(2, 4) * 0.1
        self.b1 = np.zeros((1, 4))
        self.W2 = np.random.randn(4, 1) * 0.1
        self.b2 = np.zeros((1, 1))
        self.loss_history = []

    def forward(self, X):
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = np.tanh(self.z1)  # 隱藏層激活函數
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = 1 / (1 + np.exp(-self.z2))  # 輸出層 Sigmoid
        return self.a2

    def backward(self, X, y, output):
        m = X.shape[0]
        # 輸出層梯度
        dz2 = output - y
        dW2 = np.dot(self.a1.T, dz2) / m
        db2 = np.sum(dz2, axis=0, keepdims=True) / m

        # 隱藏層梯度
        da1 = np.dot(dz2, self.W2.T)
        dz1 = da1 * (1 - np.tanh(self.z1)**2)
        dW1 = np.dot(X.T, dz1) / m
        db1 = np.sum(dz1, axis=0, keepdims=True) / m

        return dW1, db1, dW2, db2

    # 初始版本：僅支援基礎 SGD 優化器
    def train_sgd(self, X, y, epochs=500, lr=0.1):
        print("開始使用 SGD 優化器進行訓練...")
        for epoch in range(epochs):
            output = self.forward(X)
            loss = -np.mean(y * np.log(output + 1e-8) + (1 - y) * np.log(1 - output + 1e-8))
            self.loss_history.append(loss)

            # 反向傳播計算梯度
            dW1, db1, dW2, db2 = self.backward(X, y, output)

            # SGD 參數更新
            self.W1 -= lr * dW1
            self.b1 -= lr * db1
            self.W2 -= lr * dW2
            self.b2 -= lr * db2

        print(f"SGD 訓練完成！最終 Loss: {self.loss_history[-1]:.4f}")

# 執行初始訓練
if __name__ == "__main__":
    model = NeuralNetwork()
    model.train_sgd(X, y)